//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DieFledermaus.Cli.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DieFledermaus.Cli.Globalization.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entry file set..
        /// </summary>
        internal static string CreateNoEntry {
            get {
                return ResourceManager.GetString("CreateNoEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project is under development. Features and functionality are subject to change without warning..
        /// </summary>
        internal static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No archive file set..
        /// </summary>
        internal static string ExtractNoArchive {
            get {
                return ResourceManager.GetString("ExtractNoArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file does not exist: {0}.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to archive.
        /// </summary>
        internal static string HelpArchive {
            get {
                return ResourceManager.GetString("HelpArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress a file:.
        /// </summary>
        internal static string HelpCompress {
            get {
                return ResourceManager.GetString("HelpCompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompress a file:.
        /// </summary>
        internal static string HelpDecompress {
            get {
                return ResourceManager.GetString("HelpDecompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show extended help:.
        /// </summary>
        internal static string HelpHelp {
            get {
                return ResourceManager.GetString("HelpHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input filename.
        /// </summary>
        internal static string HelpInput {
            get {
                return ResourceManager.GetString("HelpInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The archive file to extract from or create..
        /// </summary>
        internal static string HelpMArchive {
            get {
                return ResourceManager.GetString("HelpMArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to create a new archive..
        /// </summary>
        internal static string HelpMCreate {
            get {
                return ResourceManager.GetString("HelpMCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file to compress..
        /// </summary>
        internal static string HelpMEntry {
            get {
                return ResourceManager.GetString("HelpMEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to extract from an existing archive..
        /// </summary>
        internal static string HelpMExtract {
            get {
                return ResourceManager.GetString("HelpMExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays this extended help..
        /// </summary>
        internal static string HelpMHelp {
            get {
                return ResourceManager.GetString("HelpMHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output filename of the compressed file..
        /// </summary>
        internal static string HelpMOut {
            get {
                return ResourceManager.GetString("HelpMOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to output filename.
        /// </summary>
        internal static string HelpOutput {
            get {
                return ResourceManager.GetString("HelpOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following parameters are mutually exclusive: {0}.
        /// </summary>
        internal static string MutuallyExclusive {
            get {
                return ResourceManager.GetString("MutuallyExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; doesn&apos;t make sense in extract-mode..
        /// </summary>
        internal static string NoEntryExtract {
            get {
                return ResourceManager.GetString("NoEntryExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; doesn&apos;t make sense in create-mode..
        /// </summary>
        internal static string NoOutputCreate {
            get {
                return ResourceManager.GetString("NoOutputCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        internal static string OverNo {
            get {
                return ResourceManager.GetString("OverNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists: {0}.
        /// </summary>
        internal static string OverwriteAlert {
            get {
                return ResourceManager.GetString("OverwriteAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite? (Y)es/(N)o.
        /// </summary>
        internal static string OverwritePrompt {
            get {
                return ResourceManager.GetString("OverwritePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file is the same as the archive file! {0}.
        /// </summary>
        internal static string OverwriteSameArchive {
            get {
                return ResourceManager.GetString("OverwriteSameArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive file is the same as the input file! {0}.
        /// </summary>
        internal static string OverwriteSameEntry {
            get {
                return ResourceManager.GetString("OverwriteSameEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        internal static string OverYes {
            get {
                return ResourceManager.GetString("OverYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple contradictory values for parameter &quot;{0}&quot;: {1}.
        /// </summary>
        internal static string ParamDup {
            get {
                return ResourceManager.GetString("ParamDup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple contradictory values for compressed file: {0}.
        /// </summary>
        internal static string ParamDupLit {
            get {
                return ResourceManager.GetString("ParamDupLit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters:.
        /// </summary>
        internal static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter format: {0}.
        /// </summary>
        internal static string ParamInvalid {
            get {
                return ResourceManager.GetString("ParamInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; does not take an argument..
        /// </summary>
        internal static string ParamNoArg {
            get {
                return ResourceManager.GetString("ParamNoArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &quot;{0}&quot; requries an argument..
        /// </summary>
        internal static string ParamReqArg {
            get {
                return ResourceManager.GetString("ParamReqArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown parameter &quot;{0}&quot;..
        /// </summary>
        internal static string ParamUnknown {
            get {
                return ResourceManager.GetString("ParamUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to archive.
        /// </summary>
        internal static string PNameArchive {
            get {
                return ResourceManager.GetString("PNameArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to archivefile.
        /// </summary>
        internal static string PNameArchiveFile {
            get {
                return ResourceManager.GetString("PNameArchiveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create.
        /// </summary>
        internal static string PNameCreate {
            get {
                return ResourceManager.GetString("PNameCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entry.
        /// </summary>
        internal static string PNameEntry {
            get {
                return ResourceManager.GetString("PNameEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extract.
        /// </summary>
        internal static string PNameExtract {
            get {
                return ResourceManager.GetString("PNameExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.
        /// </summary>
        internal static string PNameFile {
            get {
                return ResourceManager.GetString("PNameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        internal static string PNameHelp {
            get {
                return ResourceManager.GetString("PNameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input.
        /// </summary>
        internal static string PNameInput {
            get {
                return ResourceManager.GetString("PNameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to out.
        /// </summary>
        internal static string PNameOut {
            get {
                return ResourceManager.GetString("PNameOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to output.
        /// </summary>
        internal static string PNameOutput {
            get {
                return ResourceManager.GetString("PNameOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename not set! Changing output path to: {0}.
        /// </summary>
        internal static string RenameExtract {
            get {
                return ResourceManager.GetString("RenameExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of the following arguments are required: {0}.
        /// </summary>
        internal static string RequireAtLeastOne {
            get {
                return ResourceManager.GetString("RequireAtLeastOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DieFlede command-line utility.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:.
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
    }
}
