//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DieFledermaus.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Keys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Keys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DieFledermaus.Tests.Keys", typeof(Keys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;&lt;!-- Not suitable for use outside the test-app. --&gt;&lt;Modulus&gt;ur33eRUWZSZeKpYBQmTPmJjBISffR+4v7D8qZJo25yDNq2vsaDZn9RC3YOGTvXlVcXzoYXYRgEPUYK8A5br7z8lFBKAewXxCL7cbNwCCX15Xa3M4Og8WdduM4EFHqCILELRZsP8MdvAZb7wbTrDVQKpYAoa+qvT9EC5tDeBxoo7eyolaA0Prak4QNPizxGl4aiL2rXRYjd14ylJyhMg5uuhQB/qw20CekBX+6kckD0r9i47NJ5Kh1lcYZVgBSU17hO4MjTHwVynINzAoP71XEitvif6wNhFOzS9/obocXYvxXShHO9kbDfsr79ITATXkN3uV8rxSYHHwsxmYugR8NQ==&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;P&gt;8QXhT43iIedCvdpQ6jkqXW4DYiHOh0uKkz7CrrqFdXvuLbuepUTVnY8uQ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Encryption {
            get {
                return ResourceManager.GetString("Encryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;&lt;!-- Not suitable for use outside the test-app. --&gt;&lt;Modulus&gt;qjYO3OOZEV4bdBWtiXvYBC4yzSAYIX4NR4h2/StXL5m5JiEg+JhY0E5ZcfhwU8gSthVlwI0H+azEK52sciSDPwOy65ZZeopEbGrdlGODa87sQVFnma3OrpIrgbUpIAqHWrY3mWGLv5zwrzOHxfxK3IZzWaKzgDB//ktE9/lr6Vol5AAbUN86EuvXQKc6NGYc9pcOI/LHFFx3I2kR9WVYLeEQUo1fL0YPOhmuX6AD14H/rRWh5YW1DZyGqgQc/0W/dnOqeDsou8bwlyOEzIDKPsQ2hKv6pAJcwMmvWTZsPwlhsMQyxLYt4eYnYqTnJx03HmCg55kzy68PGpBwUD4McQ==&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;P&gt;6/CRbdH+gGtCkj1B788ZYpj7B3h+AVf+J9KWaWYF7g41b0YmosZGNN8Bh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
    }
}
