//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DieFledermaus.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Keys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Keys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DieFledermaus.Tests.Keys", typeof(Keys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN EC PRIVATE KEY-----
        ///Comment: Not suitable for use outside the test app.
        ///
        ///MHcCAQEEIOpS7iUPFfQbImeYqjmUmp2KXF7K1xAi2QY3G32C6JT4oAoGCCqGSM49
        ///AwEHoUQDQgAEg3BqtsRSKXjP+jnAc5D98ECPiPMOqUFPDXK6aIGOb11N2mK5YBxr
        ///0BXBCUOGeOUv6wViCRZ+GNry5uu4+Jkt4A==
        ///-----END EC PRIVATE KEY-----
        ///.
        /// </summary>
        internal static string ECDSA {
            get {
                return ResourceManager.GetString("ECDSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN RSA PRIVATE KEY-----
        ///Comment: Not suitable for use outside the test app.
        ///
        ///MIIEogIBAAKCAQEAur33eRUWZSZeKpYBQmTPmJjBISffR+4v7D8qZJo25yDNq2vs
        ///aDZn9RC3YOGTvXlVcXzoYXYRgEPUYK8A5br7z8lFBKAewXxCL7cbNwCCX15Xa3M4
        ///Og8WdduM4EFHqCILELRZsP8MdvAZb7wbTrDVQKpYAoa+qvT9EC5tDeBxoo7eyola
        ///A0Prak4QNPizxGl4aiL2rXRYjd14ylJyhMg5uuhQB/qw20CekBX+6kckD0r9i47N
        ///J5Kh1lcYZVgBSU17hO4MjTHwVynINzAoP71XEitvif6wNhFOzS9/obocXYvxXShH
        ///O9kbDfsr79ITATXkN3uV8rxSYHHwsxmYugR8NQIDAQABAoIBAFGdRcOvAi8p8hzV
        ///m25LhelQ1ZNqjCyxPlOXla0LMzSX [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Encryption {
            get {
                return ResourceManager.GetString("Encryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN RSA PRIVATE KEY-----
        ///Comment: Not suitable for use outside the test app.
        ///
        ///MIIEpQIBAAKCAQEAqjYO3OOZEV4bdBWtiXvYBC4yzSAYIX4NR4h2/StXL5m5JiEg
        ///+JhY0E5ZcfhwU8gSthVlwI0H+azEK52sciSDPwOy65ZZeopEbGrdlGODa87sQVFn
        ///ma3OrpIrgbUpIAqHWrY3mWGLv5zwrzOHxfxK3IZzWaKzgDB//ktE9/lr6Vol5AAb
        ///UN86EuvXQKc6NGYc9pcOI/LHFFx3I2kR9WVYLeEQUo1fL0YPOhmuX6AD14H/rRWh
        ///5YW1DZyGqgQc/0W/dnOqeDsou8bwlyOEzIDKPsQ2hKv6pAJcwMmvWTZsPwlhsMQy
        ///xLYt4eYnYqTnJx03HmCg55kzy68PGpBwUD4McQIDAQABAoIBAAJKDldrUNZ4z84D
        ///2AaFzb3tDVfD1mQMh2sYIbn3ehyr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
    }
}
