//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DieFledermaus.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DieFledermaus.Globalization.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DieFledermaus stream has already been successfully decrypted..
        /// </summary>
        internal static string AlreadyDecrypted {
            get {
                return ResourceManager.GetString("AlreadyDecrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The computed SHA-512 checksum did not match the expected value..
        /// </summary>
        internal static string BadChecksum {
            get {
                return ResourceManager.GetString("BadChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key or password is invalid..
        /// </summary>
        internal static string BadKey {
            get {
                return ResourceManager.GetString("BadKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified array is invalid..
        /// </summary>
        internal static string CollectBadArray {
            get {
                return ResourceManager.GetString("CollectBadArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified array is the wrong type..
        /// </summary>
        internal static string CollectBadArrayType {
            get {
                return ResourceManager.GetString("CollectBadArrayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current collection is read-only..
        /// </summary>
        internal static string CollectReadOnly {
            get {
                return ResourceManager.GetString("CollectReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of a comment must be greater than 0 and less than or equal to 65536..
        /// </summary>
        internal static string CommentLength {
            get {
                return ResourceManager.GetString("CommentLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current stream is closed..
        /// </summary>
        internal static string CurrentClosed {
            get {
                return ResourceManager.GetString("CurrentClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current stream is in read-mode..
        /// </summary>
        internal static string CurrentRead {
            get {
                return ResourceManager.GetString("CurrentRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current stream is in write-mode..
        /// </summary>
        internal static string CurrentWrite {
            get {
                return ResourceManager.GetString("CurrentWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified filename contains an unpaired surrogate character: {0}.
        /// </summary>
        internal static string FilenameBadSurrogate {
            get {
                return ResourceManager.GetString("FilenameBadSurrogate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified filename contained a non-whitespace control character..
        /// </summary>
        internal static string FilenameControl {
            get {
                return ResourceManager.GetString("FilenameControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value &quot;{0}&quot; is not a valid filename..
        /// </summary>
        internal static string FilenameDot {
            get {
                return ResourceManager.GetString("FilenameDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified filename has a length greater than 256 UTF-8 bytes..
        /// </summary>
        internal static string FilenameLengthLong {
            get {
                return ResourceManager.GetString("FilenameLengthLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified filename is empty..
        /// </summary>
        internal static string FilenameLengthZero {
            get {
                return ResourceManager.GetString("FilenameLengthZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified filename contained only whitespace characters..
        /// </summary>
        internal static string FilenameWhitespace {
            get {
                return ResourceManager.GetString("FilenameWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DieFledermaus stream contains invalid or contradictory formats..
        /// </summary>
        internal static string FormatBad {
            get {
                return ResourceManager.GetString("FormatBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DieFledermaus stream contains an invalid filename..
        /// </summary>
        internal static string FormatFilename {
            get {
                return ResourceManager.GetString("FormatFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DieFledermaus stream contains an unknown format..
        /// </summary>
        internal static string FormatUnknown {
            get {
                return ResourceManager.GetString("FormatUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream is not a valid DieFledermaus stream..
        /// </summary>
        internal static string InvalidMagicNumber {
            get {
                return ResourceManager.GetString("InvalidMagicNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified key is the wrong length..
        /// </summary>
        internal static string KeyLength {
            get {
                return ResourceManager.GetString("KeyLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An encrypted DieFledermaus stream requires a key or password..
        /// </summary>
        internal static string KeyNotSet {
            get {
                return ResourceManager.GetString("KeyNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DieFledermaus stream is not currently encrypted..
        /// </summary>
        internal static string NotEncrypted {
            get {
                return ResourceManager.GetString("NotEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value must be greater than or equal to {0} and less than or equal to {1}..
        /// </summary>
        internal static string OutOfRange {
            get {
                return ResourceManager.GetString("OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sum of the parameters &quot;{0}&quot; and &quot;{1}&quot; is greater than the length of the specified array..
        /// </summary>
        internal static string OutOfRangeLength {
            get {
                return ResourceManager.GetString("OutOfRangeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value is less than 0..
        /// </summary>
        internal static string OutOfRangeLessThanZero {
            get {
                return ResourceManager.GetString("OutOfRangeLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified password contained invalid UTF-8 characters..
        /// </summary>
        internal static string PasswordInvalidUtf8 {
            get {
                return ResourceManager.GetString("PasswordInvalidUtf8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A password must be at least 1 character long..
        /// </summary>
        internal static string PasswordZeroLength {
            get {
                return ResourceManager.GetString("PasswordZeroLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified stream is closed..
        /// </summary>
        internal static string StreamClosed {
            get {
                return ResourceManager.GetString("StreamClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified stream does not support reading..
        /// </summary>
        internal static string StreamNotReadable {
            get {
                return ResourceManager.GetString("StreamNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified stream does not support writing..
        /// </summary>
        internal static string StreamNotWritable {
            get {
                return ResourceManager.GetString("StreamNotWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DieFledermaus version number was higher than the supported maximum of the current implementation..
        /// </summary>
        internal static string VersionTooHigh {
            get {
                return ResourceManager.GetString("VersionTooHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DieFledermaus version number was lower than the supported minimum..
        /// </summary>
        internal static string VersionTooLow {
            get {
                return ResourceManager.GetString("VersionTooLow", resourceCulture);
            }
        }
    }
}
