//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DieFledermaus.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DieFledermaus.Globalization.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Die Fledermaus stream has already been successfully decrypted..
        /// </summary>
        internal static string AlreadyDecrypted {
            get {
                return ResourceManager.GetString("AlreadyDecrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The computed SHA-512 checksum did not match the expected value..
        /// </summary>
        internal static string BadChecksum {
            get {
                return ResourceManager.GetString("BadChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key or password is invalid..
        /// </summary>
        internal static string BadKey {
            get {
                return ResourceManager.GetString("BadKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current stream is closed..
        /// </summary>
        internal static string CurrentClosed {
            get {
                return ResourceManager.GetString("CurrentClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current stream is in read-mode..
        /// </summary>
        internal static string CurrentRead {
            get {
                return ResourceManager.GetString("CurrentRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current stream is in write-mode..
        /// </summary>
        internal static string CurrentWrite {
            get {
                return ResourceManager.GetString("CurrentWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Die Fledermaus stream contains an unknown format..
        /// </summary>
        internal static string FormatUnknown {
            get {
                return ResourceManager.GetString("FormatUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream is not a valid Die Fledermaus stream..
        /// </summary>
        internal static string InvalidMagicNumber {
            get {
                return ResourceManager.GetString("InvalidMagicNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified key is the wrong length..
        /// </summary>
        internal static string KeyLength {
            get {
                return ResourceManager.GetString("KeyLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An encrypted Die Fledermaus stream requires a key or password..
        /// </summary>
        internal static string KeyNotSet {
            get {
                return ResourceManager.GetString("KeyNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Die Fledermaus stream is not currently encrypted..
        /// </summary>
        internal static string NotEncrypted {
            get {
                return ResourceManager.GetString("NotEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified stream is closed..
        /// </summary>
        internal static string StreamClosed {
            get {
                return ResourceManager.GetString("StreamClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified stream does not support reading..
        /// </summary>
        internal static string StreamNotReadable {
            get {
                return ResourceManager.GetString("StreamNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified stream does not support writing..
        /// </summary>
        internal static string StreamNotWritable {
            get {
                return ResourceManager.GetString("StreamNotWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Die Fledermaus version number was higher than the supported maximum of the current implementation..
        /// </summary>
        internal static string VersionTooHigh {
            get {
                return ResourceManager.GetString("VersionTooHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Die Fledermaus version number was lower than the supported minimum..
        /// </summary>
        internal static string VersionTooLow {
            get {
                return ResourceManager.GetString("VersionTooLow", resourceCulture);
            }
        }
    }
}
